import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.github.oliverjonas.unmeta'
}

android {
    namespace 'com.github.oliverjonas.unmeta'
    compileSdk 36

    defaultConfig {
        applicationId "com.github.oliverjonas.unmeta"
        minSdk 21
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    unmeta {
        enabled = gradle.startParameter.taskNames.any { it.toLowerCase().contains('release') }
        processDependencies = true
        reportFile = layout.buildDirectory.file('outputs/logs/unmeta-report.txt')
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
}
