apply plugin: 'maven-publish'
apply plugin: 'java-gradle-plugin'
apply plugin: 'kotlin'

def getGroup = { ->
    return 'com.github.oliverjonas'
}

def getArtifact = { ->
    return 'unmeta'
}

def getVersion = { ->
    return '1.0.3'
}

buildscript {
    ext.kotlin_version = '1.4.21'
    ext.gradle_version = '3.5.3'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        //noinspection DifferentKotlinGradleVersion
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "com.android.tools.build:gradle:$gradle_version"
    }
}

repositories {
    google()
    mavenCentral()
}

gradlePlugin {
    plugins {
        create(getGroup() + '.' + getArtifact()) {
            id = getGroup() + '.' + getArtifact()
            implementationClass = getGroup() + '.' + getArtifact() + '.UnmetaPlugin'
        }
    }
}

dependencies {
    // Android gradle plugin will allow us to access Android specific features
    implementation "com.android.tools.build:gradle:$gradle_version"
    //noinspection GradleDependency
    implementation 'org.ow2.asm:asm:7.0'
}

publishing {
    publications {
        Publication(MavenPublication) {
            from components.java
            pom.withXml {
                asNode().dependencies.dependency.each { dep ->
                    dep.parent().remove(dep)
                }
            }
            group = getGroup()
            groupId = getGroup()
            artifactId = getArtifact()
            version = getVersion()
        }
    }
    repositories {
        mavenCentral()
    }
}